# Generated by Django 3.1 on 2020-12-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0002_auto_20201228_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environments',
            options={'ordering': ['date_created', 'name', 'env_stage', 'platform']},
        ),
        migrations.RenameField(
            model_name='environments',
            old_name='stage',
            new_name='env_stage',
        ),
    ]
