# Generated by Django 3.1 on 2021-01-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0004_auto_20201228_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environments',
            name='hardware',
            field=models.CharField(choices=[('PHISICAL_SERVER', 'PHISICAL_SERVER'), ('VIRTUAL MACHINE', 'VIRTUAL MACHINE'), ('CLOUD', 'CLOUD_AZURE')], max_length=50),
        ),
    ]
